name: test workflow update

on:
  push:
    branches:
      - ms-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp-dev

    permissions:  # Add this section
        id-token: write
        contents: read
        actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: projects/879339769955/locations/global/workloadIdentityPools/github-action-pool/providers/github

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Echo a message
        run: |
          echo "This is a test message from the GCP Deploy workflow using Workload Identity Federation."
